Songtronix/Airshipper

server/src/config/mod.rs
=> fix(server): wrong file ending for linux artifact

.github/workflows/artifacts.yml
Fix an issue regarding creating the msi installer artifact
=> fix(artifacts): do not error removing cached msi

.github/workflows/artifacts.yml
=> fix: fix the failed fix

Cargo.lock, client/Cargo.toml, client/src/cli/mod.rs, client/src/filesystem.rs, client/src/main.rs, client/src/network.rs, client/src/state.rs
Closes #12 
However currently it's being done quite unclean and has to be addressed later on.
=> feat: make gui optional

Cargo.lock, README.md, client/Cargo.toml, client/src/cli/mod.rs, client/src/error.rs, client/src/filesystem.rs, client/src/main.rs, client/src/network.rs, client/src/updater.rs, wix/main.wxs
=> feat: self update on windows

CHANGELOG.md, Cargo.lock, client/Cargo.toml, client/src/logger.rs, client/src/network.rs
=> Various improvements

client/Cargo.toml, client/src/network.rs
Fixes #38 and creates hotfix version `0.3.1`
=> fix(install): delete asset dir only if existent

Cargo.lock, client/src/network.rs
Little copy, paste accident happend and such the news wouldn't update anymore.
=> fix(news): update news when remote is newer

client/src/gui/mod.rs
This might fix some graphical issues people have.
=> prefer dedicated gpu by using antialiasing

Cargo.lock, client/Cargo.toml, client/src/error.rs, client/src/main.rs
=> fix: log crashes

Cargo.lock, client/Cargo.toml, client/src/logger.rs
=> update all dependencies

server/src/main.rs, server/src/routes/api.rs
fixes issue with dotenv and blocking the executor on db query.
=> Small fixes

.github/workflows/artifacts.yml, .github/workflows/check.yml, Cargo.lock, client/Cargo.toml, client/src/cli/mod.rs, client/src/consts.rs, client/src/gui/mod.rs, client/src/gui/subscriptions/download.rs, client/src/gui/update.rs, client/src/profiles.rs, client/wix/WixUI_FeatureTree.wxs, client/wix/main.wxs, server/Cargo.toml, server/src/error.rs, server/src/fairings/db.rs, server/src/main.rs
Will adjust a lot of things. See commits for details.
=> WIP: Improve CI situation

.github/workflows/artifacts.yml, .github/workflows/check.yml, CHANGELOG.md, Cargo.lock, client/src/io/fs.rs, client/src/profiles.rs, server/Cargo.toml
This will make sure that everything will be at one place.
=> set all Veloren/Voxygen env vars

Cargo.lock, client/Cargo.toml, client/src/windows.rs
https://github.com/jaemk/self_update/issues/55
=> change: use upstream fix

Cargo.lock, server/Cargo.toml, server/src/db/sqlite.rs, server/src/error.rs, server/src/lib.rs, server/src/metrics.rs, server/src/models/artifact.rs, server/src/routes/api.rs, server/src/routes/metrics.rs, server/src/routes/mod.rs
Collects very basic download statistics per OS.
=> Prometheus Statistics

.github/workflows/artifacts.yml, .github/workflows/check.yml
=> fix(ci): follow up fix for !89

client/src/cli/mod.rs, client/src/cli/parse.rs, client/src/gui/mod.rs, client/src/gui/views/default.rs, client/src/gui/views/mod.rs, client/src/gui/views/update.rs, client/src/windows.rs
Needs to be done as no terminal will show up by default now.
=> feat: Show dialog for self update (+ cli argument)

CHANGELOG.md, README.md, client/src/gui/mod.rs
=> 0.4 release

CHANGELOG.md, client/src/cli/mod.rs, client/src/gui/subscriptions/process.rs, client/src/gui/views/default.rs, client/src/io/process.rs, client/src/profiles.rs
Also removes the unnecessary CommandBuilder reimplementation.
=> Don't die on error spawning Veloren process.

client/src/profiles.rs
Changes to the enviroment variables based on #98
=> Update of Enviroment Variables

.gitignore, README.md, client/Cargo.toml, client/src/io/fs.rs, client/src/main.rs, client/src/nix.rs, client/src/profiles.rs, default.nix, flake.lock, flake.nix, shell.nix
This allows the downloaded executables to run on NixOS. Follow up to #140
=> feat: implement nixos specific executable patching
